# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main2.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(944, 602)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.add_tab = QtWidgets.QWidget()
        self.add_tab.setObjectName("add_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.add_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.camera_label = QtWidgets.QLabel(self.add_tab)
        self.camera_label.setEnabled(True)
        self.camera_label.setMinimumSize(QtCore.QSize(500, 400))
        self.camera_label.setMaximumSize(QtCore.QSize(500, 400))
        self.camera_label.setAutoFillBackground(True)
        self.camera_label.setFrameShape(QtWidgets.QFrame.Box)
        self.camera_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.camera_label.setText("")
        self.camera_label.setObjectName("camera_label")
        self.gridLayout_7.addWidget(self.camera_label, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 12, 3, 1, 1)
        self.name_lable = QtWidgets.QLabel(self.add_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.name_lable.setFont(font)
        self.name_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.name_lable.setObjectName("name_lable")
        self.gridLayout_3.addWidget(self.name_lable, 1, 2, 1, 1)
        self.reset_bt = QtWidgets.QPushButton(self.add_tab)
        self.reset_bt.setMinimumSize(QtCore.QSize(91, 31))
        self.reset_bt.setMaximumSize(QtCore.QSize(91, 31))
        self.reset_bt.setObjectName("reset_bt")
        self.gridLayout_3.addWidget(self.reset_bt, 0, 2, 1, 1)
        self.image_label = QtWidgets.QLabel(self.add_tab)
        self.image_label.setMinimumSize(QtCore.QSize(278, 181))
        self.image_label.setMaximumSize(QtCore.QSize(350, 250))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 208, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 231, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 104, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 208, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 231, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 208, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 231, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 104, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 208, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 231, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 104, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 208, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 231, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 104, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 104, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 104, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 208, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 208, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 208, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.image_label.setPalette(palette)
        self.image_label.setAutoFillBackground(True)
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.gridLayout_3.addWidget(self.image_label, 10, 3, 1, 1)
        self.name_text = QtWidgets.QLineEdit(self.add_tab)
        self.name_text.setMinimumSize(QtCore.QSize(181, 31))
        self.name_text.setMaximumSize(QtCore.QSize(250, 31))
        self.name_text.setObjectName("name_text")
        self.gridLayout_3.addWidget(self.name_text, 1, 3, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.counter_label = QtWidgets.QLabel(self.add_tab)
        self.counter_label.setMinimumSize(QtCore.QSize(101, 21))
        self.counter_label.setMaximumSize(QtCore.QSize(101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.counter_label.setFont(font)
        self.counter_label.setObjectName("counter_label")
        self.horizontalLayout_2.addWidget(self.counter_label)
        self.lcdNumber = QtWidgets.QLCDNumber(self.add_tab)
        self.lcdNumber.setMinimumSize(QtCore.QSize(64, 23))
        self.lcdNumber.setMaximumSize(QtCore.QSize(64, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.lcdNumber.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_2.addWidget(self.lcdNumber)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 4, 3, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.previousImage_bt = QtWidgets.QPushButton(self.add_tab)
        self.previousImage_bt.setMinimumSize(QtCore.QSize(141, 21))
        self.previousImage_bt.setMaximumSize(QtCore.QSize(141, 21))
        self.previousImage_bt.setObjectName("previousImage_bt")
        self.horizontalLayout_3.addWidget(self.previousImage_bt)
        self.nextImage_bt = QtWidgets.QPushButton(self.add_tab)
        self.nextImage_bt.setMinimumSize(QtCore.QSize(141, 21))
        self.nextImage_bt.setMaximumSize(QtCore.QSize(141, 21))
        self.nextImage_bt.setObjectName("nextImage_bt")
        self.horizontalLayout_3.addWidget(self.nextImage_bt)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 11, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.add_tab)
        self.label.setMinimumSize(QtCore.QSize(181, 16))
        self.label.setMaximumSize(QtCore.QSize(181, 16))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 2, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 3, 3, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.start_bt = QtWidgets.QPushButton(self.add_tab)
        self.start_bt.setEnabled(False)
        self.start_bt.setMinimumSize(QtCore.QSize(91, 31))
        self.start_bt.setMaximumSize(QtCore.QSize(91, 31))
        self.start_bt.setObjectName("start_bt")
        self.gridLayout_2.addWidget(self.start_bt, 1, 1, 1, 1)
        self.createpkl_bt = QtWidgets.QPushButton(self.add_tab)
        self.createpkl_bt.setMinimumSize(QtCore.QSize(91, 31))
        self.createpkl_bt.setMaximumSize(QtCore.QSize(91, 31))
        self.createpkl_bt.setObjectName("createpkl_bt")
        self.gridLayout_2.addWidget(self.createpkl_bt, 2, 5, 1, 1)
        self.capture_bt = QtWidgets.QPushButton(self.add_tab)
        self.capture_bt.setEnabled(False)
        self.capture_bt.setMinimumSize(QtCore.QSize(91, 31))
        self.capture_bt.setMaximumSize(QtCore.QSize(91, 31))
        self.capture_bt.setObjectName("capture_bt")
        self.gridLayout_2.addWidget(self.capture_bt, 1, 3, 1, 1)
        self.process_bt = QtWidgets.QPushButton(self.add_tab)
        self.process_bt.setEnabled(False)
        self.process_bt.setMinimumSize(QtCore.QSize(91, 31))
        self.process_bt.setMaximumSize(QtCore.QSize(91, 31))
        self.process_bt.setObjectName("process_bt")
        self.gridLayout_2.addWidget(self.process_bt, 1, 5, 1, 1)
        self.next_dataset_bt = QtWidgets.QPushButton(self.add_tab)
        self.next_dataset_bt.setEnabled(False)
        self.next_dataset_bt.setMinimumSize(QtCore.QSize(91, 31))
        self.next_dataset_bt.setMaximumSize(QtCore.QSize(91, 31))
        self.next_dataset_bt.setObjectName("next_dataset_bt")
        self.gridLayout_2.addWidget(self.next_dataset_bt, 2, 7, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 2, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 7, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 1, 6, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.add_tab, "")
        self.recognise_tab = QtWidgets.QWidget()
        self.recognise_tab.setObjectName("recognise_tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.recognise_tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.rcamera_label = QtWidgets.QLabel(self.recognise_tab)
        self.rcamera_label.setFrameShape(QtWidgets.QFrame.Box)
        self.rcamera_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rcamera_label.setText("")
        self.rcamera_label.setObjectName("rcamera_label")
        self.gridLayout_8.addWidget(self.rcamera_label, 0, 0, 1, 3)
        self.rname_label = QtWidgets.QLabel(self.recognise_tab)
        self.rname_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rname_label.setObjectName("rname_label")
        self.gridLayout_8.addWidget(self.rname_label, 0, 3, 1, 1)
        self.rstart_bt = QtWidgets.QPushButton(self.recognise_tab)
        self.rstart_bt.setMinimumSize(QtCore.QSize(91, 31))
        self.rstart_bt.setObjectName("rstart_bt")
        self.gridLayout_8.addWidget(self.rstart_bt, 1, 0, 1, 1)
        self.rrecognise_bt = QtWidgets.QPushButton(self.recognise_tab)
        self.rrecognise_bt.setMinimumSize(QtCore.QSize(91, 31))
        self.rrecognise_bt.setObjectName("rrecognise_bt")
        self.gridLayout_8.addWidget(self.rrecognise_bt, 1, 1, 1, 1)
        self.rreset_bt = QtWidgets.QPushButton(self.recognise_tab)
        self.rreset_bt.setMinimumSize(QtCore.QSize(91, 31))
        self.rreset_bt.setObjectName("rreset_bt")
        self.gridLayout_8.addWidget(self.rreset_bt, 1, 2, 1, 1)
        self.tabWidget.addTab(self.recognise_tab, "")
        self.standard_tab = QtWidgets.QWidget()
        self.standard_tab.setObjectName("standard_tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.standard_tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem9, 6, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem10, 9, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem11, 12, 0, 1, 1)
        self.st_precision_label = QtWidgets.QLabel(self.standard_tab)
        self.st_precision_label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.st_precision_label.setFont(font)
        self.st_precision_label.setAlignment(QtCore.Qt.AlignCenter)
        self.st_precision_label.setObjectName("st_precision_label")
        self.gridLayout_10.addWidget(self.st_precision_label, 1, 0, 1, 1)
        self.st_accuracy_label = QtWidgets.QLabel(self.standard_tab)
        self.st_accuracy_label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.st_accuracy_label.setFont(font)
        self.st_accuracy_label.setAlignment(QtCore.Qt.AlignCenter)
        self.st_accuracy_label.setObjectName("st_accuracy_label")
        self.gridLayout_10.addWidget(self.st_accuracy_label, 7, 0, 1, 1)
        self.st_recall_label = QtWidgets.QLabel(self.standard_tab)
        self.st_recall_label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.st_recall_label.setFont(font)
        self.st_recall_label.setAlignment(QtCore.Qt.AlignCenter)
        self.st_recall_label.setObjectName("st_recall_label")
        self.gridLayout_10.addWidget(self.st_recall_label, 4, 0, 1, 1)
        self.st_precision_result = QtWidgets.QLabel(self.standard_tab)
        self.st_precision_result.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.st_precision_result.setFont(font)
        self.st_precision_result.setAlignment(QtCore.Qt.AlignCenter)
        self.st_precision_result.setObjectName("st_precision_result")
        self.gridLayout_10.addWidget(self.st_precision_result, 2, 0, 1, 1)
        self.st_recall_result = QtWidgets.QLabel(self.standard_tab)
        self.st_recall_result.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.st_recall_result.setFont(font)
        self.st_recall_result.setAlignment(QtCore.Qt.AlignCenter)
        self.st_recall_result.setObjectName("st_recall_result")
        self.gridLayout_10.addWidget(self.st_recall_result, 5, 0, 1, 1)
        self.st_time_result = QtWidgets.QLabel(self.standard_tab)
        self.st_time_result.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.st_time_result.setFont(font)
        self.st_time_result.setAlignment(QtCore.Qt.AlignCenter)
        self.st_time_result.setObjectName("st_time_result")
        self.gridLayout_10.addWidget(self.st_time_result, 11, 0, 1, 1)
        self.st_time_label = QtWidgets.QLabel(self.standard_tab)
        self.st_time_label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.st_time_label.setFont(font)
        self.st_time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.st_time_label.setObjectName("st_time_label")
        self.gridLayout_10.addWidget(self.st_time_label, 10, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem12, 3, 0, 1, 1)
        self.st_accuracy_result = QtWidgets.QLabel(self.standard_tab)
        self.st_accuracy_result.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.st_accuracy_result.setFont(font)
        self.st_accuracy_result.setAlignment(QtCore.Qt.AlignCenter)
        self.st_accuracy_result.setObjectName("st_accuracy_result")
        self.gridLayout_10.addWidget(self.st_accuracy_result, 8, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.st_process_bt = QtWidgets.QPushButton(self.standard_tab)
        self.st_process_bt.setMinimumSize(QtCore.QSize(200, 31))
        self.st_process_bt.setMaximumSize(QtCore.QSize(200, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.st_process_bt.setFont(font)
        self.st_process_bt.setObjectName("st_process_bt")
        self.horizontalLayout_5.addWidget(self.st_process_bt)
        self.gridLayout_10.addLayout(self.horizontalLayout_5, 13, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem13, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_10, 0, 1, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.st_face_Dataset_group = QtWidgets.QGroupBox(self.standard_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.st_face_Dataset_group.setFont(font)
        self.st_face_Dataset_group.setObjectName("st_face_Dataset_group")
        self.st_radioButton_d1 = QtWidgets.QRadioButton(self.st_face_Dataset_group)
        self.st_radioButton_d1.setGeometry(QtCore.QRect(20, 30, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.st_radioButton_d1.setFont(font)
        self.st_radioButton_d1.setChecked(True)
        self.st_radioButton_d1.setObjectName("st_radioButton_d1")
        self.st_radioButton_d4 = QtWidgets.QRadioButton(self.st_face_Dataset_group)
        self.st_radioButton_d4.setGeometry(QtCore.QRect(220, 80, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.st_radioButton_d4.setFont(font)
        self.st_radioButton_d4.setObjectName("st_radioButton_d4")
        self.st_radioButton_d2 = QtWidgets.QRadioButton(self.st_face_Dataset_group)
        self.st_radioButton_d2.setGeometry(QtCore.QRect(220, 30, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.st_radioButton_d2.setFont(font)
        self.st_radioButton_d2.setObjectName("st_radioButton_d2")
        self.st_radioButton_d3 = QtWidgets.QRadioButton(self.st_face_Dataset_group)
        self.st_radioButton_d3.setGeometry(QtCore.QRect(20, 80, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.st_radioButton_d3.setFont(font)
        self.st_radioButton_d3.setObjectName("st_radioButton_d3")
        self.st_maxdata_spinbox = QtWidgets.QSpinBox(self.st_face_Dataset_group)
        self.st_maxdata_spinbox.setGeometry(QtCore.QRect(140, 120, 71, 22))
        self.st_maxdata_spinbox.setMinimum(100)
        self.st_maxdata_spinbox.setMaximum(10000)
        self.st_maxdata_spinbox.setProperty("value", 200)
        self.st_maxdata_spinbox.setObjectName("st_maxdata_spinbox")
        self.st_maxdata_label = QtWidgets.QLabel(self.st_face_Dataset_group)
        self.st_maxdata_label.setGeometry(QtCore.QRect(40, 120, 101, 21))
        self.st_maxdata_label.setObjectName("st_maxdata_label")
        self.gridLayout_11.addWidget(self.st_face_Dataset_group, 0, 0, 1, 1)
        self.st_feature_Extraction_group = QtWidgets.QGroupBox(self.standard_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.st_feature_Extraction_group.setFont(font)
        self.st_feature_Extraction_group.setObjectName("st_feature_Extraction_group")
        self.st_radioButton_LBPH = QtWidgets.QRadioButton(self.st_feature_Extraction_group)
        self.st_radioButton_LBPH.setGeometry(QtCore.QRect(20, 40, 121, 41))
        self.st_radioButton_LBPH.setChecked(True)
        self.st_radioButton_LBPH.setObjectName("st_radioButton_LBPH")
        self.st_radioButton_LMDEP = QtWidgets.QRadioButton(self.st_feature_Extraction_group)
        self.st_radioButton_LMDEP.setGeometry(QtCore.QRect(20, 90, 101, 41))
        self.st_radioButton_LMDEP.setObjectName("st_radioButton_LMDEP")
        self.gridLayout_11.addWidget(self.st_feature_Extraction_group, 1, 0, 1, 1)
        self.st_classifiers_group = QtWidgets.QGroupBox(self.standard_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.st_classifiers_group.setFont(font)
        self.st_classifiers_group.setObjectName("st_classifiers_group")
        self.st_radioButton_ED = QtWidgets.QRadioButton(self.st_classifiers_group)
        self.st_radioButton_ED.setGeometry(QtCore.QRect(230, 30, 191, 31))
        self.st_radioButton_ED.setObjectName("st_radioButton_ED")
        self.st_radioButton_KNN = QtWidgets.QRadioButton(self.st_classifiers_group)
        self.st_radioButton_KNN.setGeometry(QtCore.QRect(230, 70, 111, 31))
        self.st_radioButton_KNN.setObjectName("st_radioButton_KNN")
        self.st_radioButton_SVM = QtWidgets.QRadioButton(self.st_classifiers_group)
        self.st_radioButton_SVM.setGeometry(QtCore.QRect(30, 70, 111, 31))
        self.st_radioButton_SVM.setObjectName("st_radioButton_SVM")
        self.st_radioButton_RF = QtWidgets.QRadioButton(self.st_classifiers_group)
        self.st_radioButton_RF.setGeometry(QtCore.QRect(30, 30, 171, 31))
        self.st_radioButton_RF.setChecked(True)
        self.st_radioButton_RF.setObjectName("st_radioButton_RF")
        self.st_horizontalSlider = QtWidgets.QSlider(self.st_classifiers_group)
        self.st_horizontalSlider.setGeometry(QtCore.QRect(160, 120, 281, 22))
        self.st_horizontalSlider.setMinimum(10)
        self.st_horizontalSlider.setMaximum(90)
        self.st_horizontalSlider.setSingleStep(10)
        self.st_horizontalSlider.setProperty("value", 70)
        self.st_horizontalSlider.setTracking(True)
        self.st_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.st_horizontalSlider.setInvertedControls(False)
        self.st_horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.st_horizontalSlider.setTickInterval(10)
        self.st_horizontalSlider.setObjectName("st_horizontalSlider")
        self.label_2 = QtWidgets.QLabel(self.st_classifiers_group)
        self.label_2.setGeometry(QtCore.QRect(70, 120, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.st_slidervalue_lineEdit = QtWidgets.QLineEdit(self.st_classifiers_group)
        self.st_slidervalue_lineEdit.setGeometry(QtCore.QRect(460, 120, 41, 20))
        self.st_slidervalue_lineEdit.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.st_slidervalue_lineEdit.setObjectName("st_slidervalue_lineEdit")
        self.gridLayout_11.addWidget(self.st_classifiers_group, 2, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.standard_tab)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_9.addWidget(self.progressBar, 1, 0, 1, 1)
        self.tabWidget.addTab(self.standard_tab, "")
        self.analysis1_tab = QtWidgets.QWidget()
        self.analysis1_tab.setObjectName("analysis1_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.analysis1_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.an_process_lbph_bt = QtWidgets.QPushButton(self.analysis1_tab)
        self.an_process_lbph_bt.setObjectName("an_process_lbph_bt")
        self.gridLayout_5.addWidget(self.an_process_lbph_bt, 1, 0, 1, 1)
        self.an_LBPH_label = QtWidgets.QLabel(self.analysis1_tab)
        self.an_LBPH_label.setMinimumSize(QtCore.QSize(448, 384))
        self.an_LBPH_label.setMaximumSize(QtCore.QSize(640, 480))
        self.an_LBPH_label.setFrameShape(QtWidgets.QFrame.Box)
        self.an_LBPH_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.an_LBPH_label.setText("")
        self.an_LBPH_label.setObjectName("an_LBPH_label")
        self.gridLayout_5.addWidget(self.an_LBPH_label, 0, 0, 1, 1)
        self.an_LMDEP_label = QtWidgets.QLabel(self.analysis1_tab)
        self.an_LMDEP_label.setMinimumSize(QtCore.QSize(448, 384))
        self.an_LMDEP_label.setFrameShape(QtWidgets.QFrame.Box)
        self.an_LMDEP_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.an_LMDEP_label.setText("")
        self.an_LMDEP_label.setObjectName("an_LMDEP_label")
        self.gridLayout_5.addWidget(self.an_LMDEP_label, 0, 1, 1, 1)
        self.an_process_lmdep_bt = QtWidgets.QPushButton(self.analysis1_tab)
        self.an_process_lmdep_bt.setObjectName("an_process_lmdep_bt")
        self.gridLayout_5.addWidget(self.an_process_lmdep_bt, 1, 1, 1, 1)
        self.tabWidget.addTab(self.analysis1_tab, "")
        self.analysis2_tab = QtWidgets.QWidget()
        self.analysis2_tab.setObjectName("analysis2_tab")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.analysis2_tab)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.scrollArea = QtWidgets.QScrollArea(self.analysis2_tab)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 400))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 883, 1011))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.an2_face_Dataset_group = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.an2_face_Dataset_group.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.an2_face_Dataset_group.setFont(font)
        self.an2_face_Dataset_group.setObjectName("an2_face_Dataset_group")
        self.an2_radioButton_d1 = QtWidgets.QRadioButton(self.an2_face_Dataset_group)
        self.an2_radioButton_d1.setGeometry(QtCore.QRect(20, 30, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.an2_radioButton_d1.setFont(font)
        self.an2_radioButton_d1.setChecked(True)
        self.an2_radioButton_d1.setObjectName("an2_radioButton_d1")
        self.an2_radioButton_d4 = QtWidgets.QRadioButton(self.an2_face_Dataset_group)
        self.an2_radioButton_d4.setGeometry(QtCore.QRect(220, 80, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.an2_radioButton_d4.setFont(font)
        self.an2_radioButton_d4.setObjectName("an2_radioButton_d4")
        self.an2_radioButton_d2 = QtWidgets.QRadioButton(self.an2_face_Dataset_group)
        self.an2_radioButton_d2.setGeometry(QtCore.QRect(220, 30, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.an2_radioButton_d2.setFont(font)
        self.an2_radioButton_d2.setObjectName("an2_radioButton_d2")
        self.an2_radioButton_d3 = QtWidgets.QRadioButton(self.an2_face_Dataset_group)
        self.an2_radioButton_d3.setGeometry(QtCore.QRect(20, 80, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.an2_radioButton_d3.setFont(font)
        self.an2_radioButton_d3.setObjectName("an2_radioButton_d3")
        self.horizontalLayout.addWidget(self.an2_face_Dataset_group)
        self.an2_classifiers_group = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.an2_classifiers_group.setMinimumSize(QtCore.QSize(500, 150))
        self.an2_classifiers_group.setMaximumSize(QtCore.QSize(525, 150))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.an2_classifiers_group.setFont(font)
        self.an2_classifiers_group.setObjectName("an2_classifiers_group")
        self.an2_radioButton_ED = QtWidgets.QRadioButton(self.an2_classifiers_group)
        self.an2_radioButton_ED.setGeometry(QtCore.QRect(230, 30, 191, 31))
        self.an2_radioButton_ED.setObjectName("an2_radioButton_ED")
        self.an2_radioButton_KNN = QtWidgets.QRadioButton(self.an2_classifiers_group)
        self.an2_radioButton_KNN.setGeometry(QtCore.QRect(230, 70, 111, 31))
        self.an2_radioButton_KNN.setObjectName("an2_radioButton_KNN")
        self.an2_radioButton_SVM = QtWidgets.QRadioButton(self.an2_classifiers_group)
        self.an2_radioButton_SVM.setGeometry(QtCore.QRect(30, 70, 111, 31))
        self.an2_radioButton_SVM.setObjectName("an2_radioButton_SVM")
        self.an2_radioButton_RF = QtWidgets.QRadioButton(self.an2_classifiers_group)
        self.an2_radioButton_RF.setGeometry(QtCore.QRect(30, 30, 171, 31))
        self.an2_radioButton_RF.setChecked(True)
        self.an2_radioButton_RF.setObjectName("an2_radioButton_RF")
        self.an2_horizontalSlider = QtWidgets.QSlider(self.an2_classifiers_group)
        self.an2_horizontalSlider.setGeometry(QtCore.QRect(140, 120, 281, 22))
        self.an2_horizontalSlider.setMinimum(10)
        self.an2_horizontalSlider.setMaximum(90)
        self.an2_horizontalSlider.setSingleStep(10)
        self.an2_horizontalSlider.setProperty("value", 70)
        self.an2_horizontalSlider.setTracking(True)
        self.an2_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.an2_horizontalSlider.setInvertedControls(False)
        self.an2_horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.an2_horizontalSlider.setTickInterval(10)
        self.an2_horizontalSlider.setObjectName("an2_horizontalSlider")
        self.label_3 = QtWidgets.QLabel(self.an2_classifiers_group)
        self.label_3.setGeometry(QtCore.QRect(50, 120, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.an2_slidervalue_lineEdit_2 = QtWidgets.QLineEdit(self.an2_classifiers_group)
        self.an2_slidervalue_lineEdit_2.setGeometry(QtCore.QRect(430, 120, 41, 20))
        self.an2_slidervalue_lineEdit_2.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.an2_slidervalue_lineEdit_2.setObjectName("an2_slidervalue_lineEdit_2")
        self.horizontalLayout.addWidget(self.an2_classifiers_group)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.an2_process_bt = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.an2_process_bt.setObjectName("an2_process_bt")
        self.verticalLayout.addWidget(self.an2_process_bt)
        self.an2_image_Label_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.an2_image_Label_1.setMinimumSize(QtCore.QSize(0, 400))
        self.an2_image_Label_1.setMaximumSize(QtCore.QSize(16777215, 400))
        self.an2_image_Label_1.setFrameShape(QtWidgets.QFrame.Box)
        self.an2_image_Label_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.an2_image_Label_1.setLineWidth(2)
        self.an2_image_Label_1.setMidLineWidth(1)
        self.an2_image_Label_1.setText("")
        self.an2_image_Label_1.setObjectName("an2_image_Label_1")
        self.verticalLayout.addWidget(self.an2_image_Label_1)
        self.an2_image_Label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.an2_image_Label_2.setMinimumSize(QtCore.QSize(0, 400))
        self.an2_image_Label_2.setMaximumSize(QtCore.QSize(16777215, 400))
        self.an2_image_Label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.an2_image_Label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.an2_image_Label_2.setLineWidth(2)
        self.an2_image_Label_2.setMidLineWidth(1)
        self.an2_image_Label_2.setText("")
        self.an2_image_Label_2.setObjectName("an2_image_Label_2")
        self.verticalLayout.addWidget(self.an2_image_Label_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_12.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.analysis2_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name_lable.setText(_translate("MainWindow", "Name"))
        self.reset_bt.setText(_translate("MainWindow", "Reset"))
        self.counter_label.setText(_translate("MainWindow", "Image Captured"))
        self.previousImage_bt.setText(_translate("MainWindow", "back"))
        self.nextImage_bt.setText(_translate("MainWindow", "Next"))
        self.label.setText(_translate("MainWindow", "* Press Enter To Submit"))
        self.start_bt.setText(_translate("MainWindow", "Start"))
        self.createpkl_bt.setText(_translate("MainWindow", "Create Pikle"))
        self.capture_bt.setText(_translate("MainWindow", "Capture"))
        self.process_bt.setText(_translate("MainWindow", "Process"))
        self.next_dataset_bt.setText(_translate("MainWindow", "Next"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.add_tab), _translate("MainWindow", "Add"))
        self.rname_label.setText(_translate("MainWindow", "Details of Person"))
        self.rstart_bt.setText(_translate("MainWindow", "Start"))
        self.rrecognise_bt.setText(_translate("MainWindow", "Recognise"))
        self.rreset_bt.setText(_translate("MainWindow", "Reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.recognise_tab), _translate("MainWindow", "Recognise"))
        self.st_precision_label.setText(_translate("MainWindow", "Precision"))
        self.st_accuracy_label.setText(_translate("MainWindow", "Accuracy"))
        self.st_recall_label.setText(_translate("MainWindow", "Recall"))
        self.st_precision_result.setText(_translate("MainWindow", "0"))
        self.st_recall_result.setText(_translate("MainWindow", "0"))
        self.st_time_result.setText(_translate("MainWindow", "0"))
        self.st_time_label.setText(_translate("MainWindow", "Time"))
        self.st_accuracy_result.setText(_translate("MainWindow", "0"))
        self.st_process_bt.setText(_translate("MainWindow", "Process"))
        self.st_face_Dataset_group.setTitle(_translate("MainWindow", "Face Dataset"))
        self.st_radioButton_d1.setText(_translate("MainWindow", "Face94"))
        self.st_radioButton_d4.setText(_translate("MainWindow", "FEI"))
        self.st_radioButton_d2.setText(_translate("MainWindow", "Face95"))
        self.st_radioButton_d3.setText(_translate("MainWindow", "Face96"))
        self.st_maxdata_label.setText(_translate("MainWindow", "Max Data"))
        self.st_feature_Extraction_group.setTitle(_translate("MainWindow", "Feature Extraction"))
        self.st_radioButton_LBPH.setText(_translate("MainWindow", "LBPH"))
        self.st_radioButton_LMDEP.setText(_translate("MainWindow", "LMDEP"))
        self.st_classifiers_group.setTitle(_translate("MainWindow", "Classifiers"))
        self.st_radioButton_ED.setText(_translate("MainWindow", "Euclidean Distance"))
        self.st_radioButton_KNN.setText(_translate("MainWindow", "KNN"))
        self.st_radioButton_SVM.setText(_translate("MainWindow", "SVM"))
        self.st_radioButton_RF.setText(_translate("MainWindow", "Random Forest"))
        self.label_2.setText(_translate("MainWindow", "Training %"))
        self.st_slidervalue_lineEdit.setText(_translate("MainWindow", "70"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.standard_tab), _translate("MainWindow", "Standard"))
        self.an_process_lbph_bt.setText(_translate("MainWindow", "LBPH"))
        self.an_process_lmdep_bt.setText(_translate("MainWindow", "LMDEP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.analysis1_tab), _translate("MainWindow", "Analysis 1"))
        self.an2_face_Dataset_group.setTitle(_translate("MainWindow", "Face Dataset"))
        self.an2_radioButton_d1.setText(_translate("MainWindow", "Face94"))
        self.an2_radioButton_d4.setText(_translate("MainWindow", "FEI"))
        self.an2_radioButton_d2.setText(_translate("MainWindow", "Face95"))
        self.an2_radioButton_d3.setText(_translate("MainWindow", "Face96"))
        self.an2_classifiers_group.setTitle(_translate("MainWindow", "Classifiers"))
        self.an2_radioButton_ED.setText(_translate("MainWindow", "Euclidean Distance"))
        self.an2_radioButton_KNN.setText(_translate("MainWindow", "KNN"))
        self.an2_radioButton_SVM.setText(_translate("MainWindow", "SVM"))
        self.an2_radioButton_RF.setText(_translate("MainWindow", "Random Forest"))
        self.label_3.setText(_translate("MainWindow", "Training %"))
        self.an2_slidervalue_lineEdit_2.setText(_translate("MainWindow", "70"))
        self.an2_process_bt.setText(_translate("MainWindow", "Process"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.analysis2_tab), _translate("MainWindow", "Analysis 2"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
